# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sat, 16 Jul 2022 18:09:31 +0000
*               @ALL          0
*               @user         8
