<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Sat, 16 Jul 2022 18:09:31 +0000
 */
$conf['title'] = 'The Pleistocene Project';
$conf['lang'] = 'en';
$conf['license'] = 'cc-by-nc';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
