# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Sat, 16 Jul 2022 18:09:31 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

tppharry:$2y$10$Ek27KPQWihIGFRBxttbgVeAfMvT.609KdC/4Dm0wU1grzkNcqLXaC:Harry Chew:harry@tech13.co.uk:admin,user
tpphenri:$2y$10$8SMrSzGeIkqducEOfcFIhOs7M18vUCZO9TRdbGn4LiVVx4XdXpj46:Henri:haapakangas.henri@gmail.com:admin,user
tppnoe:$2y$10$ATCTYFrHc6EcuC8J68TxD.h8EW4n63.kBPkd5EFRi4fA7Irf8pNhu:Noé:noemathieu@hotmail.fr:user
